# Generated by Django 5.2.4 on 2025-08-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuentry',
            name='meal_type',
            field=models.CharField(max_length=10),
        ),
    ]
