# Generated by Django 5.2.4 on 2025-07-16 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0008_alter_household_options_household_default_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.JSONField(blank=True, default=list)),
                ('household', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='floorplan', to='main.household')),
            ],
        ),
    ]
