# Generated by Django 5.2.4 on 2025-07-12 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_household_user_delete_item_delete_todolist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='households',
        ),
        migrations.AddField(
            model_name='user',
            name='household',
            field=models.ForeignKey(blank=True, help_text='The single household this user belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='main.household'),
        ),
    ]
