# Generated by Django 5.2.4 on 2025-07-13 17:18

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_user_households_user_household'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='code',
            field=models.CharField(default=main.models.generate_household_code, help_text='Invite code for others to join.', max_length=8),
        ),
    ]
