# Generated by Django 5.2.4 on 2025-07-13 17:29

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_household_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='code',
            field=models.CharField(default=main.models.generate_household_code, help_text='Invite code for others to join.', max_length=8, unique=True),
        ),
    ]
