# Generated by Django 5.2.4 on 2025-07-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_household_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('LEI', 'Romanian Leu')], default='CHF', help_text='Your preferred currency.', max_length=3),
        ),
    ]
