# Generated by Django 5.2.4 on 2025-07-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_household_default_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='household',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='household',
            name='default_language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('ja', 'Japanese'), ('fr', 'French'), ('es', 'Spanish'), ('it', 'Italian'), ('ro', 'Romanian')], default='en', help_text='Default language for the household.', max_length=10),
        ),
        migrations.AddField(
            model_name='household',
            name='gamification_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='household',
            name='household_shop',
            field=models.BooleanField(default=False),
        ),
    ]
