# Generated by Django 5.2.4 on 2025-08-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_household_options_household_default_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='meal_count',
            field=models.PositiveIntegerField(default=3, help_text='Number of meals per day'),
        ),
    ]
