# Generated by Django 5.2.4 on 2025-08-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_household_meal_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='meal_count',
            field=models.PositiveIntegerField(help_text='Number of meals per day'),
        ),
    ]
