# Generated by Django 5.2.4 on 2025-07-13 17:29

import django.db.models.deletion
import expenses.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0005_alter_household_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in your currency.', max_digits=10)),
                ('description', models.CharField(blank=True, help_text='Optional description of the expense.', max_length=255)),
                ('date', models.DateField(auto_now_add=True, help_text='Date the expense was created.')),
                ('code', models.CharField(default=expenses.models.generate_expense_code, help_text='Unique code for this expense record.', max_length=8, unique=True)),
                ('household', models.ForeignKey(blank=True, help_text='If set, this expense is shared with the household.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_expenses', to='main.household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
