# Generated by Django 5.2.4 on 2025-07-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_converted_amount_expense_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='scope',
            field=models.CharField(choices=[('private', 'Private'), ('shared', 'Shared')], default='private', max_length=7),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(),
        ),
    ]
